/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cc_demo_jni_NativeWrapper */

#ifndef _Included_com_cc_demo_jni_NativeWrapper
#define _Included_com_cc_demo_jni_NativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cc_demo_jni_NativeWrapper
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cc_demo_jni_NativeWrapper_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
